/**
 * Embedding storage and hybrid search.
 *
 * Objects can carry a vector embedding (generated by Hermes during
 * research runs). When present, the search system combines FTS
 * relevance with cosine similarity for hybrid retrieval.
 *
 * Requires the pgvector extension (migration 0004).
 */
import { sql, and, eq, isNotNull, isNull } from 'drizzle-orm';
import { schema } from '@hermieos/db';
import { getDb } from './db.js';

/**
 * Store an embedding vector for an object. The embedding should be a
 * fixed-length float array (e.g. 1536 for OpenAI ada-002 or equivalent).
 * Hermes is responsible for generating embeddings during research runs.
 */
export async function setObjectEmbedding(
  userId: string,
  objectId: string,
  embedding: number[],
): Promise<void> {
  const db = getDb();
  const embeddingStr = `[${embedding.join(',')}]`;
  await db.execute(sql`
    UPDATE objects
    SET embedding = ${embeddingStr}::vector
    WHERE id = ${objectId}::uuid
      AND user_id = ${userId}::uuid
  `);
}

/**
 * Hybrid search combining FTS relevance (ts_rank_cd) with cosine
 * vector similarity. When an embedding query is provided, the final
 * score is a weighted blend:
 *
 *   score = fts_weight × ts_rank_cd + vector_weight × (1 - cosine_distance)
 *
 * Defaults to 0.7 FTS / 0.3 vector.
 *
 * If no embedding query is provided or the object has no embedding,
 * falls back to pure FTS.
 */
export async function hybridSearch(
  userId: string,
  input: {
    query: string;
    embeddingQuery?: number[];
    type?: schema.ObjectRow['type'];
    limit: number;
    ftsWeight?: number;
  },
): Promise<
  Array<{
    id: string;
    title: string;
    summary: string | null;
    type: string;
    rank: number;
    snippet: string;
    vectorScore: number | null;
  }>
> {
  const db = getDb();
  const ftsW = input.ftsWeight ?? 0.7;
  const vecW = 1 - ftsW;
  const conditions = [eq(schema.objects.userId, userId), isNull(schema.objects.archivedAt)];
  if (input.type) conditions.push(eq(schema.objects.type, input.type));

  const tsq = sql`websearch_to_tsquery('english', ${input.query})`;
  conditions.push(sql`search_vector @@ ${tsq}`);

  const hasEmbedding = input.embeddingQuery && input.embeddingQuery.length > 0;

  let vectorPart = sql``;
  if (hasEmbedding) {
    const vecStr = `[${input.embeddingQuery!.join(',')}]`;
    vectorPart = sql`, ${vecW} * (1 - (embedding <=> ${vecStr}::vector)) AS vector_score`;
  }

  const rows = await db.execute(sql`
    SELECT
      id, title, summary, type,
      ${ftsW} * ts_rank_cd(search_vector, ${tsq}) AS rank,
      coalesce(
        ts_headline(
          'english',
          coalesce(title, '') || ' ' || coalesce(summary, ''),
          ${tsq},
          'StartSel=<mark>, StopSel=</mark>, MaxFragments=1, MaxWords=20, MinWords=5'
        ),
        ''
      ) AS snippet
      ${vectorPart}
    FROM objects
    WHERE ${and(...conditions)}
      ${hasEmbedding ? sql`AND embedding IS NOT NULL` : sql``}
    ORDER BY ${hasEmbedding ? sql`(rank + vector_score) DESC` : sql`rank DESC`}
    LIMIT ${input.limit}
  `);

  const list = (Array.isArray(rows) ? rows : []) as Array<{
    id: string; title: string; summary: string | null; type: string;
    rank: number; snippet: string; vector_score?: number | null;
  }>;

  return list.map((r) => ({
    id: r.id,
    title: r.title,
    summary: r.summary,
    type: r.type,
    rank: r.rank,
    snippet: r.snippet,
    vectorScore: r.vector_score ?? null,
  }));
}
