/**
 * Hermes profile config generator.
 *
 * Reads the per-user `mcp_token` from Postgres and writes a HermieOS
 * Hermes profile's `config.yaml` and `.env` so Hermes can:
 *   1. Connect to the HermieOS MCP server with the per-user bearer.
 *   2. Expose the API server on a known port with a known key.
 *   3. Scope Honcho memory by `X-Hermes-Session-Key` per user.
 *
 * Idempotent: re-runs are safe; existing files are overwritten with
 * the current token. Re-run after every token rotation.
 *
 * Env:
 *   DATABASE_URL             - Postgres URL (required)
 *   HERMES_USER_EMAIL        - HermieOS user email to provision (required)
 *   HERMES_PROFILE_NAME      - Hermes profile dir, default 'default'
 *   HERMES_HOME              - Hermes data root, default /opt/hermes
 *   HERMES_API_PORT          - API server port for this profile (default 8642)
 *   HERMES_API_HOST          - API server bind host (default 127.0.0.1)
 *   HERMES_API_KEY           - API server bearer (default: generated)
 *   HERMES_MCP_URL           - URL of the HermieOS MCP server
 *                              (default http://mcp:3002/mcp)
 *   HERMES_MODEL             - Default model for the agent (default 'hermes-agent')
 *   HERMES_INFERENCE_PROVIDER- 'auto' / 'portal' / 'custom' (default 'auto')
 *   HERMES_INFERENCE_BASE_URL- Required when provider=custom
 *   HERMES_INFERENCE_API_KEY - Required when provider=custom
 *   HERMES_GENERATE_KEY      - '1' to auto-generate API_KEY on first run
 */
import { randomBytes } from 'node:crypto';
import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { eq } from 'drizzle-orm';
import { createDatabase, closeDatabase, schema } from '@hermieos/db';

if (!process.env.DATABASE_URL) {
  // eslint-disable-next-line no-console
  console.error('DATABASE_URL is required');
  process.exit(1);
}
if (!process.env.HERMES_USER_EMAIL) {
  // eslint-disable-next-line no-console
  console.error('HERMES_USER_EMAIL is required');
  process.exit(1);
}

const PROFILE = process.env.HERMES_PROFILE_NAME ?? 'default';
const HOME = process.env.HERMES_HOME ?? '/opt/hermes';
const PROFILE_DIR = join(HOME, 'profiles', PROFILE);
const ENV_FILE = join(PROFILE_DIR, '.env');
const CONFIG_FILE = join(PROFILE_DIR, 'config.yaml');

const db = createDatabase({ url: process.env.DATABASE_URL });

interface KeySecret {
  value: string;
  generated: boolean;
}

function readOrGenerateKey(path: string, generateEnv: string): KeySecret {
  // Prefer explicit env var
  if (process.env[generateEnv]) {
    return { value: process.env[generateEnv]!, generated: false };
  }
  // Reuse existing if present
  if (existsSync(path)) {
    const txt = readFileSync(path, 'utf8');
    const m = txt.match(/^API_SERVER_KEY=(.+)$/m);
    if (m && m[1] && m[1].length >= 8) {
      return { value: m[1], generated: false };
    }
  }
  // Generate fresh
  return { value: randomBytes(32).toString('hex'), generated: true };
}

function buildYaml(input: {
  mcpUrl: string;
  mcpToken: string;
  model: string;
  inferenceProvider: string;
  inferenceBaseUrl: string | undefined;
}): string {
  const lines: string[] = [];
  lines.push('# Generated by hermieos/scripts/hermes-profile-gen.ts');
  lines.push('# Do not edit by hand — re-run the generator after a token rotation.');
  lines.push('');
  lines.push('model:');
  lines.push(`  default: ${input.model}`);
  lines.push(`  provider: ${input.inferenceProvider}`);
  if (input.inferenceBaseUrl) {
    lines.push(`  base_url: ${input.inferenceBaseUrl}`);
  }
  lines.push('');
  lines.push('mcp_servers:');
  lines.push('  hermieos:');
  lines.push(`    url: ${input.mcpUrl}`);
  lines.push('    headers:');
  lines.push(`      Authorization: "Bearer ${input.mcpToken}"`);
  lines.push('    enabled: true');
  lines.push('    tools:');
  lines.push('      resources: false');
  lines.push('      prompts: false');
  lines.push('');
  lines.push('tool_loop_guardrails:');
  lines.push('  hard_stop_enabled: true');
  lines.push('  hard_stop_after:');
  lines.push('    exact_failure: 5');
  lines.push('    idempotent_no_progress: 5');
  lines.push('');
  return lines.join('\n');
}

function buildEnv(input: {
  apiKey: string;
  apiHost: string;
  apiPort: string;
}): string {
  return [
    '# Generated by hermieos/scripts/hermes-profile-gen.ts',
    `# API server settings for the '${PROFILE}' profile`,
    `API_SERVER_ENABLED=true`,
    `API_SERVER_HOST=${input.apiHost}`,
    `API_SERVER_PORT=${input.apiPort}`,
    `API_SERVER_KEY=${input.apiKey}`,
    `API_SERVER_MODEL_NAME=${PROFILE}`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  // 1. find the user
  const email = process.env.HERMES_USER_EMAIL!;
  const [user] = await db
    .select({ id: schema.users.id, mcpToken: schema.users.mcpToken, email: schema.users.email })
    .from(schema.users)
    .where(eq(schema.users.email, email))
    .limit(1);
  if (!user) {
    // eslint-disable-next-line no-console
    console.error(`No HermieOS user with email ${email}`);
    process.exit(1);
  }
  if (!user.mcpToken) {
    // eslint-disable-next-line no-console
    console.error(`User ${email} has no mcp_token yet`);
    process.exit(1);
  }

  // 2. ensure profile dir
  mkdirSync(PROFILE_DIR, { recursive: true });

  // 3. generate / reuse API key
  const apiKey = readOrGenerateKey(ENV_FILE, 'HERMES_API_KEY');
  const apiHost = process.env.HERMES_API_HOST ?? '127.0.0.1';
  const apiPort = process.env.HERMES_API_PORT ?? '8642';
  const mcpUrl = process.env.HERMES_MCP_URL ?? 'http://mcp:3002/mcp';
  const model = process.env.HERMES_MODEL ?? 'hermes-agent';
  const inferenceProvider = process.env.HERMES_INFERENCE_PROVIDER ?? 'auto';
  const inferenceBaseUrl = process.env.HERMES_INFERENCE_BASE_URL;

  // 4. write config.yaml
  const yaml = buildYaml({
    mcpUrl,
    mcpToken: user.mcpToken,
    model,
    inferenceProvider,
    inferenceBaseUrl,
  });
  writeFileSync(CONFIG_FILE, yaml, { encoding: 'utf8', mode: 0o600 });
  // eslint-disable-next-line no-console
  console.log(`wrote ${CONFIG_FILE} (mcp_url=${mcpUrl})`);

  // 5. write .env
  const env = buildEnv({ apiKey: apiKey.value, apiHost, apiPort });
  writeFileSync(ENV_FILE, env, { encoding: 'utf8', mode: 0o600 });
  // eslint-disable-next-line no-console
  console.log(`wrote ${ENV_FILE} (api_key=${apiKey.generated ? 'GENERATED' : 'reused'})`);

  await closeDatabase(db);
}

main().catch(async (err) => {
  // eslint-disable-next-line no-console
  console.error('profile generator failed:', err);
  await closeDatabase(db);
  process.exit(1);
});
